version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - db
    command: --quiet
    container_name: db
  frontend:
    image: codelit/courselit-frontend:latest
    environment:
      - MAIN_URL=${MAIN_URL}
      - BACKEND=${MAIN_URL}${API_PREFIX}
      - API_PREFIX=${API_PREFIX}
    expose:
      - "3000"
    depends_on:
      - backend
    container_name: frontend
  backend:
    image: codelit/courselit-backend:latest
    environment:
      - API_PREFIX=${API_PREFIX}
      - MEDIA_FOLDER=/
      - DB_CONNECTION_STRING=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ${MOUNT_UPLOAD_FOLDER_VOLUME_AS}:/uploads
      - ${MOUNT_THUMBNAIL_FOLDER_VOLUME_AS}:/thumbs
    expose:
      - "8000"
    depends_on:
      - db
    container_name: backend
  proxy:
    image: codelit/courselit-proxy:latest
    environment:
      - API_PREFIX=${API_PREFIX}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    container_name: proxy

volumes:
  db:
#   uploads:
#     driver: local
#     driver_opts:
#       device: ${MOUNT_UPLOAD_FOLDER_VOLUME_AS}
#       o: bind
#   thumbs:
#     driver: local
#     driver_opts:
#       device: ${MOUNT_THUMBNAIL_FOLDER_VOLUME_AS}
#       o: bind