# Reset the Docker service
- name: Unmask Docker
  command: systemctl unmask docker

- name: Bounce Docker service
  systemd:
    name: docker
    state: restarted

# Install Certbot
- name: Install certbot
  apt: update_cache=yes name=certbot state=present

# Collect user's email address if she wants to setup SSL
- pause:
    prompt: "Enter a valid email for getting emails from Let's Encrypt about your SSL certificate."
  register: prompt
  when: not use_existing_installation

- set_fact:
    email: "{{ prompt.user_input }}"
  when: not use_existing_installation

# Acquire certificate
- name: Run certbot
  command: certbot certonly --standalone --non-interactive --agree-tos -m {{ email }} -d {{ domain }}

# Combine certificates
- name: Combine certificates
  shell:
      cmd: cat fullchain.pem privkey.pem > haproxy.pem
      chdir: /etc/letsencrypt/live/{{ domain }}/
      creates: haproxy.pem