name: Prettier
on: [push]

jobs:
  backend-prettier:
    name: Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Prettifying backend
      run: |
        npm install
        npm run prettier
      working-directory: ./backend

  frontend-prettier:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Prettifying frontend
      run: |
        npm install
        npm run prettier
      working-directory: ./frontend